openapi: 3.1.0
info:
  version: 1.0.0
  title: AppFeature2
  contact:
    email: contact@robowealth.co.th
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  description:
    $ref: ./info-description.md
tags:
  - name: WatchList
    description: WatchList
  - name: Notification
    description: Notification
  - name: Note
    description: Note
servers:
  - url: "https://example.com"
paths:
  #// Watch List
  /api/v1/watch_list/list/{customer_id}:
    $ref: paths/watchList.yaml
  /api/v1/watch_list/update-name:
    $ref: paths/watchList.yaml/#/UpdateNameWatchList
  /api/v1/watch_list/delete-assets:
    $ref: paths/watchList.yaml/#/DeleteAssets
  /api/v1/watch_list/position-assets:
    $ref: paths/watchList.yaml/#/PositionAssest
  /api/v1/watch_list/insert-assets:
    $ref: paths/watchList.yaml/#/InsertAssetsToWatchList
  /api/v1/watch_list/move:
    $ref: paths/watchList.yaml/#/MoveWatchList
  /api/v1/watch_list/copy:
    $ref: paths/watchList.yaml/#/CopyWatchList
    #// Notification
  /api/v1/notification/count-notification:
    $ref: paths/notification.yaml/#/CountNotification
  /api/v1/notification/notification-list:
    $ref: paths/notification.yaml/#/NotificationList
  /api/v1/notification/notification-read:
    $ref: paths/notification.yaml/#/NotificationRead
  /api/v1/notification/notification-read-all:
    $ref: paths/notification.yaml/#/NotificationReadAll
  /api/v1/notification/delete-notification:
    $ref: paths/notification.yaml/#/DeleteNotification
  /api/v1/notification/delete-notification-all:
    $ref: paths/notification.yaml/#/DeleteNotificationAll
    #// Note
  /api/v1/note/count-note:
    $ref: paths/note.yaml/#/CountNote
  /api/v1/note/insert-note-to-asset:
    $ref: paths/note.yaml/#/InsertNoteToAsset
  /api/v1/note/inquiry-note-detail:
    $ref: paths/note.yaml/#/InquiryNoteDetail
  /api/v1/note/update-note-detail:
    $ref: paths/note.yaml/#/UpdateNoteDetail
  /api/v1/note/delete-note:
    $ref: paths/note.yaml/#/DeleteNote
  /api/v1/note/inquiry-article-list:
    $ref: paths/note.yaml/#/InquiryArticleList
  /api/v1/note/inquiry-bookmarked:
    $ref: paths/note.yaml/#/InquiryBookmarked
  /api/v1/note/insert-articleNote-asset:
    $ref: paths/note.yaml/#/InsertArticleNote
  /api/v1/note/inquiry-count-all-type-note:
    $ref: paths/note.yaml/#/CountAllTypeNote
  /api/v1/note/inquiry-asset-list-related-Article:
    $ref: paths/note.yaml/#/InquiryAssetListArticle

   
  /api/v1/note/insert-bookmark:
    $ref: paths/note.yaml/#/InsertBookmark
  /api/v1/note/insert-bookmark-asset-list:
    $ref: paths/note.yaml/#/InsertBookmarkAssetList
  /api/v1/note/inquiry-bookmarked-article-list:
    $ref: paths/note.yaml/#/InquiryBookmarkedAssetList
  /api/v1/note/delete-bookmarked-article:
    $ref: paths/note.yaml/#/DeleteBookmarkedArticle
  /api/v1/note/delete-asset-by-bookmark:
    $ref: paths/note.yaml/#/DeleteAssetByBookmark
  #// Card
  /api/v1/note/inquiry-card-note:
    $ref: paths/note.yaml/#/InquiryCardNote
  /api/v1/note/inquiry-note-all:
    $ref: paths/note.yaml/#/InquiryNoteAll

  #// Alert
  /api/v1/note/insert-alert-note:
    $ref: paths/note.yaml/#/InsertAlertNote
    
  #// Portfolio
  /api/v1/note/insert-portfolio-note:
    $ref: paths/note.yaml/#/InsertPortfolioNote
  /api/v1/note/delete-portfolio-note:
    $ref: paths/note.yaml/#/DeletePortfolioNote
  /api/v1/note/delete-portfolio-note-all:
    $ref: paths/note.yaml/#/DeletePortfolioNoteAll


  

     
  
    


     

