openapi: 3.1.0
info:
  version: 1.0.0
  title: AppFeature2
  contact:
    email: contact@robowealth.co.th
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  description:
    $ref: ./info-description.md
tags:
  - name: WatchList
    description: WatchList
  - name: Note
    description: Note
servers:
  - url: "https://example.com"
paths:
  # //Watch List
  /api/v1/watch_list/list/{customer_id}:
    $ref: paths/watchList.yaml
  /api/v1/watch_list/update-name:
    $ref: paths/watchList.yaml/#/UpdateNameWatchList
  /api/v1/watch_list/delete-assets:
    $ref: paths/watchList.yaml/#/DeleteAssets
  /api/v1/watch_list/position-assets:
    $ref: paths/watchList.yaml/#/PositionAssest
  
